---
- hosts: all

  vars:
    user: phillipalexander
    home_dir: "/Users/{{ user }}"
    application_dir: "{{ home_dir }}/Applications"
    caskroom_dir: /opt/homebrew-cask/Caskroom
    applications:
      - alfred
      - flux
      - firefox
      - google-chrome
      - handbrake
      - hipchat
      - vlc
      - brackets
      - notational-velocity
      - licecap
      - dash
      - kaleidoscope
      - appcleaner
      - google-drive
      - sublime-text3
      - slate
      - notational-velocity
      - transmission
    brews:
      - ack
      - hub
      - rsync
      - zsh
      - mongodb
      - figlet
      - sqlite
      - tree
      - wget
      - htop
      - tmux
      - fasd

  tasks:
      - include: tasks/homebrew.yml tags=homebrew
      - include: tasks/files.yml tags=files
